### ISSUE TITLE
Unknown type name 'half' during compiling chamfer distance

### ISSUE THREAD

**Issue by jiangzhongshi** [ThibaultGROUEIX/3D-CODED#1]
Hi,

I am trying to build and run the code. However, during building chamfer distance `python build.py`, my compilers complain about 
```
Including CUDA code.
/home/zhjiang/Workspace/3D-CODED/nndistance
generating /tmp/tmpXnfonZ/_my_lib.c
setting the current directory to '/tmp/tmpXnfonZ'
running build_ext
building '_my_lib' extension
creating home
creating home/zhjiang
creating home/zhjiang/Workspace
creating home/zhjiang/Workspace/3D-CODED
creating home/zhjiang/Workspace/3D-CODED/nndistance
creating home/zhjiang/Workspace/3D-CODED/nndistance/src
gcc -pthread -B /home/zhjiang/anaconda3/envs/py2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zhjiang/anaconda3/envs/py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zhjiang/anaconda3/envs/py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zhjiang/anaconda3/envs/py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zhjiang/anaconda3/envs/py2/include/python2.7 -c _my_lib.c -o ./_my_lib.o
In file included from /home/zhjiang/anaconda3/envs/py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCBlas.h:5:0,
                 from /home/zhjiang/anaconda3/envs/py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:6,
                 from _my_lib.c:493:
/home/zhjiang/anaconda3/envs/py2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCHalf.h:16:49: error: unknown type name 'half'
 THC_EXTERNC void THCFloat2Half(THCState *state, half *out, float *in, ptrdiff_t len);
```

I think there might be some version issues here, but I fail to find a solution.

My gcc is 5.5.0, pytorch=0.1.12_2, python=2.7

Any help would be appreciated!

Best,
Zhongshi

**Comment by jiangzhongshi** [comment]
With gcc-6, it's the same error

**Comment by ThibaultGROUEIX** [comment]
Hi,
Recompile the .cu file with nvcc, and try with gcc4.8, 5 and 6. It's my best guess...
Best regards,
Thibault

**Comment by jiangzhongshi** [comment]
Thanks to the prompt reply. It seems that I solved the compilation problem by `export CC=g++`, and compiled them as C++. Don't know if there are any implications...

**Comment by jiangzhongshi** [comment]
After this. there's another bug:
```
| => python inference/correspondences.py 
computing correspondences for data/example_0.ply and data/example_1.ply
cleaning ...
('number of point before : ', 177638)
('number of point after : ', 177453)
Traceback (most recent call last):
  File "inference/correspondences.py", line 105, in <module>
    reconstruct.reconstruct(opt.inputA)
  File "/home/zhjiang/Workspace/3D-CODED/inference/reconstruct.py", line 187, in reconstruct
    mesh, meshReg = run(input, scalefactor)
  File "/home/zhjiang/Workspace/3D-CODED/inference/reconstruct.py", line 82, in run
    pointsReconstructed = global_variables.network(points_LR)
  File "/home/zhjiang/anaconda3/envs/py2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "./auxiliary/model.py", line 165, in forward
    rand_grid = self.vertex.transpose(0,1).contiguous().unsqueeze(0).expand(x.size(0), 3,-1)
RuntimeError: The expanded size of the tensor (-1) must match the existing size (6890) at               non-singleton dimension 2. at /py/conda-bld/pytorch_1493676237139/work/torch/lib/TH/THStorage.c:99

```

which from what I can see, is a bug in early pytorch https://github.com/pytorch/pytorch/issues/3196.

This is quite easy to workaround though, just to let you know. Thanks

**Comment by ThibaultGROUEIX** [comment]
thanks !
i really appreciate your feedback ! i déveloped in pytorch v4 and wasn't aware of this issue with v12. i'll update tomorrow.
keep me posted,
Thibault

**Comment by jiangzhongshi** [comment]
Yes. It seems that there are several places are actually migrated to higher versions of pytorch, including the occurrence of `torch.no_grad`, `torch.matmul`. 

I don't think they are issues worth of attention, since I believe you will migrate everything to future pytorch.

Also, I have another question, with running your example code, one of the examples gives reconstruction like the following, is it expected?
![screenshot from 2018-07-25 16-20-32](https://user-images.githubusercontent.com/12759319/43233840-2d0f1df4-902d-11e8-9565-c520198b1a5d.png)

**Comment by ThibaultGROUEIX** [comment]
Hey,
I updated the readme with : 
- use pytorch 0.4.0a0+ea02833 instead of v1.12 to avoid retrocompatibility issues
- I added the reconstruction you're supposed to get in ```/data```+ visualization in the README.md

I've done a lot of updates yesterday. you could try to : 
- make sure you have the last version
- send me the initial guess in your failure example. If the initial guess is correct, it likely to be an issue with the Chamfer distance during optimization. 

Best regards,
Thibault

**Comment by ThibaultGROUEIX** [comment]
![initguess](https://user-images.githubusercontent.com/11445067/43254100-e8ddf908-90c6-11e8-83a0-588d8fd32502.png)
Initial guess you should get; This is a very easy example, so the intial guess is already close to optimum.

**Comment by jiangzhongshi** [comment]
Thanks! It works now. Thanks for the nice work! It also works amazingly well on a monster model I have. BTW, do you have any idea on processing unaligned model? Can I get 24 orientation and choose the best one in terms of some distance?

**Comment by ThibaultGROUEIX** [comment]
hey ! yes Mat sent me your results :) great work! can i add them in the README?  they re cool!
for unaligned meshes : 
- i already choose the best rotation around Y axis in "reconstruct.py".
- if you're not aligned on any axis, i would try, say 300 random 3d rotations and pick the one that have the best reconstruction in terms of chamfer distance. You can add that in "reconstruct.py" and you can find code that uniformly sample a 3d rotation in "datasetsmpl.py" (its commented).

We can exchange by skype over this if you want ! (i could also use your advice on the Adobe fellowship. i would like to apply for 2019).
