### ISSUE TITLE
Bad result of example 0

### ISSUE THREAD

**Issue by lrquad** [ThibaultGROUEIX/3D-CODED#10]
Followed the install instructions and run the code with default parameters.
The example 1 is fine but example 0 looks bad.
Could you please check it? Maybe the trained model is different with yours?
Thanks very much!

![bad_result00](https://user-images.githubusercontent.com/1467970/58991631-59133100-87ae-11e9-8ae3-988c04f374f9.png)

**Comment by asnt** [comment]
@lrquad , I got the same result. Did you solve this?

**Comment by ThibaultGROUEIX** [comment]
@lrquad
Sorry for the late reply. 
I will release my train and test files on **monday**. The issue could be with your generated data.
Best regards,
Thibault
