### ISSUE TITLE
Someone please help with seemingly easy fix

### ISSUE THREAD

**Issue by BingEdison** [ThibaultGROUEIX/3D-CODED#13]
Howdy!

Setup : windows10    running     ubuntu 16.04
all prior dependencies have been installed but running python in ubuntu  inference/correspondences.py
yields error . Any idea as to what is happening or solutions would be greatly appreciated

Thanks in advance.
 
WARNING:root:Setting up a new session...
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=51 error=30 : unknown error
Traceback (most recent call last):
  File "inference/correspondences.py", line 85, in <module>
    global_variables.network = AE_AtlasNet_Humans(num_points=opt.num_points)
  File "./auxiliary/model.py", line 134, in __init__
    self.vertex = torch.from_numpy(point_set).cuda().float()
  File "/home/user/venv/lib/python3.5/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:51

**Comment by ThibaultGROUEIX** [comment]
Dear @EdisonBing,
I have unfortunately no idea what could be going on. I don't have experience with windows. 
This looks like a pytorch issue though, unrelated to 3D-CODED.
Maybe you could validate this by running a minimal script calling `torch.from_numpy(point_set).cuda().float()`.

@fmassa could you give your expert opinion please?
Best regards,
Thibault

**Comment by ThibaultGROUEIX** [comment]
@EdisonBing Were you able to fix this bug?
Regards, Thibault

**Comment by BingEdison** [comment]
I was not installing in windows but Linux has worked fine.

**Comment by ThibaultGROUEIX** [comment]
Great ! Thanks for the feedback!
