### ISSUE TITLE
I have run script.py  and found that the result "FinalReconstruction.ply" is Finding files is a two-dimensional image rather than a three-dimensional image

### ISSUE THREAD

**Issue by jayis520** [ThibaultGROUEIX/3D-CODED#17]
Hi
        I have downloaded  the latest code,run script.py  and found that the result "XXXFinalReconstruction.ply" is a two-dimensional image rather than a three-dimensional image.This result is different from that of the code version in August,which result "XXXFinalReconstruction.ply" is a three-dimensional image.

**Comment by ThibaultGROUEIX** [comment]
Hi @jayis520 ,
Glad you solved it!
What was the issue?
best regards,
Thibault

**Comment by jayis520** [comment]
> Hi @jayis520 ,
> Glad you solved it!
> What was the issue?
> best regards,
> Thibault

Because I run "./inference/script.py" directly according to  the document "README".I see the code and find it need add "--dir name" to reload the model flow.But the old code don't need it.This is my ridiculous mistake.By the way, May I ask your email address?Sometimes,I really need your help. Thank you!
