### ISSUE TITLE
The problem"OSError: [Errno 12] Cannot allocate memory" when runing "python ./training/train.py "

### ISSUE THREAD

**Issue by jayis520** [ThibaultGROUEIX/3D-CODED#18]
Hi
     I was trying to run model training command "python ./training/train.py ",it reports:
```
python ./training/train.py 

Used fix seed
Random Seed:  1
WARNING:root:Setting up a new session...
creating folder   log/02019-10-03T11:24:32.317276
PARAMETER: 
         batch_size : 32
         workers : 10
         nepoch : 100
         start_epoch : 0
         randomize : False
         lrate : 0.001
         lr_decay_1 : 80
         lr_decay_2 : 90
         number_points : 2500
         faust : INTER
         id : 0
         env : CODED
         display : True
         port : 8889
         dir_name : log/02019-10-03T11:24:32.317276
         dataset_path : ./export/
         model : 
         point_translation : False
         dim_template : 3
         patch_deformation : False
         dim_out_patch : 3
         start_from : TEMPLATE
         accelerated_chamfer : True
         HR : True
         LR_input : True
         reg_num_steps : 3000
         inputA : data/example_0.ply
         inputB : data/example_1.ply
         num_angles : 100
         clean : True
         scale : True
         project_on_target : False
         date : 2019-10-03 11:24:32.317268
         logname : log/02019-10-03T11:24:32.317276/log.txt
         checkpointname : log/02019-10-03T11:24:32.317276/optimizer_last.pth
         reload : False
git repo path :  https://github.com/ThibaultGROUEIX/3D-CODED/commit/
Ellapsed time to load dataset:  129.85412502288818
num_vertices 6890
Ellapsed time to load dataset:  0.11727118492126465
num_vertices 6890
num_vertices 6890
Using template to initialize template
bottleneck_size 1027
Traceback (most recent call last):
  File "./training/train.py", line 24, in <module>
    trainer.train_epoch()
  File "/media/lab601/000555B8000E726C/wuy/3D-CODED/training/trainer.py", line 114, in train_epoch
    iterator = self.dataloader_train.__iter__()
  File "/home/lab601/anaconda2/envs/pytorch-3D-CODED/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "/home/lab601/anaconda2/envs/pytorch-3D-CODED/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in __init__
    w.start()
  File "/home/lab601/anaconda2/envs/pytorch-3D-CODED/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/lab601/anaconda2/envs/pytorch-3D-CODED/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/lab601/anaconda2/envs/pytorch-3D-CODED/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/lab601/anaconda2/envs/pytorch-3D-CODED/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/lab601/anaconda2/envs/pytorch-3D-CODED/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
     I see the code,and find the problem is in dataset.py
       _if self.train:
            self.datas = torch.load("./data/datas_surreal_train.pth")
        else:
            self.datas = torch.load("./data/datas_surreal_test.pth")_
     The size of file "datas_surreal_train.pth" is 18G，but my computor's GPU memory size is 11G.How can I solve this problem?

**Comment by ThibaultGROUEIX** [comment]
You can just add some ram if you can or use the pretrained models,
Note that what you need is CPU memory and not GPU.
best regards 
Thibault

**Comment by jayis520** [comment]
> You can just add some ram if you can or use the pretrained models,
> Note that what you need is CPU memory and not GPU.
> best regards
> Thibault

Thank you for your  reply.How do I generate these two files ‘datas_surreal_train.pth’ and 'datas_surreal_test.pth'?

**Comment by ThibaultGROUEIX** [comment]
just use the provided script `download_dataset.sh`

**Comment by jayis520** [comment]
Hi
@ThibaultGROUEIX 
Yes, I have downloaded these files.
Because the file  ‘datas_surreal_train.pth‘  is too big, I want to regenerate a smaller file.
Can you tell me the following way?

**Comment by ThibaultGROUEIX** [comment]
Hi you can look at how the data was generated here 👍 https://github.com/ThibaultGROUEIX/3D-CODED/blob/master/data/README.md
I am afraid it's not so straightforward
Cheers,
Thibault

**Comment by jayis520** [comment]
> Hi you can look at how the data was generated here 👍 https://github.com/ThibaultGROUEIX/3D-CODED/blob/master/data/README.md
> I am afraid it's not so straightforward
> Cheers,
> Thibault

Hi,
I also did this step" https://github.com/ThibaultGROUEIX/3D-CODED/blob/master/data/README.md"，generating the database contains four folders “dataset-bent、dataset-bent-val、dataset-surreal、dataset-surreal-val”.but all four folders are XXX.ply files.How do I generate .pth files?
Thank you!

**Comment by ThibaultGROUEIX** [comment]
`.pth` are generated by stacking all the training samples in a large pytorch tensor of shape `Num_training_samples, num_points, 3`
