### ISSUE TITLE
Where  is MPI-FAUST/training/ref/reg_color_ref.ply?

### ISSUE THREAD

**Issue by zeal-up** [ThibaultGROUEIX/3D-CODED#2]
Thanks for your jobs. The README file is detailed。
However, in generate_data_human.py, there exist one file I can't find.
```
mesh_ref = pymesh.load_mesh("/home/thibault/Downloads/MPI-FAUST/training/ref/reg_color_ref.ply")
```
I have download MPI-FAUST dataset, but the sub-directory [training] has no directory named [ref]. 

Also, it seems that the MPI-FAUST dataset you used is different from what I download from the website. Do you sure that you download the FAUST dataset from http://faust.is.tue.mpg.de/challenge/Inter-subject_challenge . And you have no further process?

**Comment by ThibaultGROUEIX** [comment]
Hi @zeal-github 

Thanks for pointing this out.
```reg_color_ref``` is just the first training example of FAUST; centered and colorized. I've included it in ``` template/template_color.ply ```. You can ```git pull```.

Best regards,
Thibault

**Comment by zeal-up** [comment]
@ThibaultGROUEIX Thanks for your reply.
I can't create a conda env using this file `auxiliary/pytorch-atalasnet.yml`.
Conda put out a error
```
 ValueError: Incompatible component merge:
      - '0'
      - 'h1d4fec5_0'
```
I don't know why.
My configuration:
system: ubuntu 14/16
conda: ananconda3

I just want to make sure that the `.yml` file is latest.

**Comment by ThibaultGROUEIX** [comment]
Yes, you're wright, there was a weird issue.
I commited an update of the list of dependencies and ran a clean install. it worked for me.
Best regards,
Thibault
