### ISSUE TITLE
./data/download_template.sh failed

### ISSUE THREAD

**Issue by jellyDL** [ThibaultGROUEIX/3D-CODED#21]
Thank you for your great work！
and cloud.enpc.fr maybe unstable, download_template.sh always return unavailable, could you give another download address? thank you!

**Comment by ThibaultGROUEIX** [comment]
Hi @hzwangjl,  
The cloud is down for the day for maintenance and will be back up tomorrow, can you wait until then ?Cheers,
Thibault

**Comment by jellyDL** [comment]
> Hi @hzwangjl,
> The cloud is down for the day for maintenance and will be back up tomorrow, can you wait until then ?Cheers,
> Thibault

yeah, it‘s done now！ thankyou！
