### ISSUE TITLE
Solution to flipped reconstruction 

### ISSUE THREAD

**Issue by yanghtr** [ThibaultGROUEIX/3D-CODED#22]
I tested the code and met the flipped reconstruction. According to the readme:
"Sometimes the reconstruction is flipped, which break the correspondences. In the easiest case where you meshes are registered in the same orientation, you can just fix this angle in reconstruct.py line 86, to avoid the flipping problem. Also note from this line that the angle search only looks in [-90°,+90°]."

However, it seems that there is no `reconstruct.py` in this master repo. I wonder how to solve the filpped reconstruction problem. Thank you very much.

**Comment by ThibaultGROUEIX** [comment]
Hi @yanghtr ,

Sorry it's actually here https://github.com/ThibaultGROUEIX/3D-CODED/blob/master/inference/correspondences.py#L240-L241.
I've updated the readme.
The best vertical angle is searched  in [-90°,+90°] L240. I added in the new version a search in "bending angle" of  [-45°,+45] L241

Best regards,
Thibault

**Comment by yanghtr** [comment]
Thank you very much for your reply!
