### ISSUE TITLE
FAUST inter dataset download zip corrupt, could you please share MPI-Faust.zip?

### ISSUE THREAD

**Issue by AmmonZ** [ThibaultGROUEIX/3D-CODED#23]
![image](https://user-images.githubusercontent.com/18216061/81060584-5ca2c100-8f05-11ea-8877-0ed5e28fed0d.png)
![image](https://user-images.githubusercontent.com/18216061/81060639-7512db80-8f05-11ea-99d4-e59e3d647471.png)

I try to download this Faust dataset mentioned in script.py, but it's slow and the final zip is corrupted after trying download from many PCs.

**Comment by ThibaultGROUEIX** [comment]
Hi @AmmonZ ,
Is it an issue with a file provided by 3D-CODED or with a download from http://faust.is.tue.mpg/de ?
Best regards
Thibault

**Comment by AmmonZ** [comment]
Yes, And I found a MPI-dataset download link in the legacy commit, which solves this. Thank you!

**Comment by ThibaultGROUEIX** [comment]
Hi @AmmonZ,
Can you detail what was the problem for future users? It's unclear to me if it was an issue with the depo or with Faust website?
Cheers,
