### ISSUE TITLE
trained model failed

### ISSUE THREAD

**Issue by Alision-Yan** [ThibaultGROUEIX/3D-CODED#25]
The trained model seems to have failed. Can you share  again？

**Comment by ThibaultGROUEIX** [comment]
hi @Alision-Yan,
Can you share an error message please? is it a download issue, code issue, package version... ?
best regards,
Thibault

**Comment by Alision-Yan** [comment]
is download issue

**Comment by ThibaultGROUEIX** [comment]
Please be as precise as possible, which link is not working and what is the error message?

**Comment by Alision-Yan** [comment]
https://drive.google.com/file/d/1ZAjOuTaeDrKJbFffzLnLn_K-C86fYCXs/view this link is not working and the error message is:
 抱歉，您目前无法查看或下载此文件。

最近查看或下载此文件的用户过多。请稍后再尝试访问此文件。如果您尝试访问的文件特别大或由很多人一起共享，则可能需要长达 24 小时才能查看或下载该文件。如果 24 小时后您仍然无法访问文件，请与您的域管理员联系。

**Comment by ThibaultGROUEIX** [comment]
The download link works fine for me. Maybe you've got a network issue? I cannot read Chinese unfortunately.
Best,
Thibault

**Comment by Alision-Yan** [comment]
Oh,I have  solved this problem,must register with Google Cloud disk to download it @ThibaultGROUEIX

**Comment by ThibaultGROUEIX** [comment]
Ok thanks for the feedback !
