### ISSUE TITLE
I want to use the VAE of convolution operation to reconstruct the model.

### ISSUE THREAD

**Issue by cainiaoshidai** [ThibaultGROUEIX/3D-CODED#26]
Dear professor,
I want to use the VAE of convolution operation to reconstruct the model to  get better correspondence. Can you give me some suggestions. Thank you very much.
best

**Comment by ThibaultGROUEIX** [comment]
Dear @cainiaoshidai ,

Thanks for reaching out
I did not understand what you meant. Can you reformulate please?

-Best regards,
-Thibault

**Comment by cainiaoshidai** [comment]
> Dear @cainiaoshidai ,
> 
> Thanks for reaching out
> I did not understand what you meant. Can you reformulate please?
> 
> -Best regards,
> -Thibault

Thank you.  I have solved it.
