### ISSUE TITLE
How to improve the training speed

### ISSUE THREAD

**Issue by qiji77** [ThibaultGROUEIX/3D-CODED#27]
First of all, thank you for this wonderful work!
I'm training a batch now, about six minutes,

How long does it take you to train? My GPU usage rate is only 22%.
Is there any way to improve your training speed? Thank you very much. All the best

**Comment by ThibaultGROUEIX** [comment]
Hi @qiji77 ,
Maybe try with more dataloader workers? 
Best,
-Thibault

**Comment by qiji77** [comment]
Thank you for your reply. I'll try it now！
