### ISSUE TITLE
How to compute the error?

### ISSUE THREAD

**Issue by cathylacus** [ThibaultGROUEIX/3D-CODED#30]
In the compare experiments ,How to compute error? Because like FMNet,inputing two shape and computing their error,But your code is template and sample,so computing correspondencing error within template and sample? or comput the error within input shape and Deformed template?
![image](https://user-images.githubusercontent.com/63350070/116494207-ec8a0980-a8d2-11eb-81f0-f205573ed3b5.png)

**Comment by ThibaultGROUEIX** [comment]
Hi @cathylacus,

In 3D-CODED, you reconstruct both shapes by deformation of the common template. Then you can compute correspondences via nearest neighbours. Please refer to the paper or the slides for a more detailed explanation.

Best regards
