### ISSUE TITLE
About unsup_training

### ISSUE THREAD

**Issue by qiji77** [ThibaultGROUEIX/3D-CODED#31]
Hello,
    It's a great job. However, I encountered a problem when using 3D-CODED(from tag v2.0.0 ) to train unsupervised model. I can't get the same ideal result as in the paper. Could you provide your trained model? It will be very helpful to me, look forward to your reply.
    Best

**Comment by ThibaultGROUEIX** [comment]
Hi @qiji77 
It should be in this zip : it's a 3 years old zip, so i am not 100% sure it's the model used in the paper but there are high chances it is.
https://cloud.enpc.fr/s/n4L7jqD486V8IJn
Best regards,
Thibault

**Comment by qiji77** [comment]
Thanks for your help！
Best regards,
Diaojunqi&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月8日(星期二) 下午4:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] About unsup_training (#31)





 
Hi @qiji77
 It should be in this zip : it's a 3 years old zip, so i am not 100% sure it's the model used in the paper but there are high chances it is.
 https://cloud.enpc.fr/s/n4L7jqD486V8IJn
 Best regards,
 Thibault

**Comment by zhoaliang** [comment]
> Hello, It's a great job. However, I encountered a problem when using 3D-CODED(from tag v2.0.0 ) to train unsupervised model. I can't get the same ideal result as in the paper. Could you provide your trained model? It will be very helpful to me, look forward to your reply. Best

I would like to try something new using this code for unsupervised training, but currently cannot find network.mesh while training. Could you provide something about how to use it? It will be very helpful to me, look forward to your reply.
best~

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with  3D-CODED
Cheers,
Thibault
