### ISSUE TITLE
About dataset processing

### ISSUE THREAD

**Issue by cainiaoshidai** [ThibaultGROUEIX/3D-CODED#32]
Hi,

     I need to align the trunk axis to the Y axis when processing the dataset, so what should I do?  Can you give me some advice?

Thanks,

**Comment by ThibaultGROUEIX** [comment]
Hi @cainiaoshidai, 

Can you give me more info? What is your data, what are you trying to achieve?

Best,
Thibault

**Comment by cainiaoshidai** [comment]
Thanks,
I want process the dataset of Shrec, but I don't know how to align the trunk axis to the Y axis.

**Comment by ThibaultGROUEIX** [comment]
If all your meshes are consistently oriented in your dataset, you could open them in meshlab and look for the rotation that aligns the trunk to the Y axis.
