### ISSUE TITLE
Results of computing correspondences

### ISSUE THREAD

**Issue by kuzand** [ThibaultGROUEIX/3D-CODED#35]
Hello! After running the `python inference/correspondences.py --dir_name learning_elementary_structure_trained_models/1patch_deformation` using the provided trained model and the example meshes, I got a folder named `results` which contains two files: `correspondences.ply` and `correspondences.txt`. I was expecting to get pairs of points {(q_r, q_t)}, however we just get a list of point coordinates (in total 177638 points). I am not sure how to interpret these results and how to get the colored meshes as in the readme file.

**Comment by ThibaultGROUEIX** [comment]
HI, 
Thanks for reaching out and using the code. 

Most likely in `correspondences.txt` you have the list of matching points on the surface of mesh 2 of every point in mesh 1. You can check this by making sure `correspondences.txt` has the same number of points of mesh 1 for instance.

`correspondences.ply` is the list of closest points in `correspondences.txt` with the faces of mesh 1 as shown here : https://github.com/ThibaultGROUEIX/3D-CODED/blob/master/inference/correspondences.py#L112

cheers,
Thibault

**Comment by kuzand** [comment]
Thanks for the reply! That makes sense now.

I was wondering though how to generate the colors to show the correspondences. In `my_utils.py` there is a function `get_colors()` Is it the one you used for the vertex colors?

**Comment by ThibaultGROUEIX** [comment]
Yes, I think i just colorised the template and propagated to mesh 1 and mesh 2

**Comment by caijinana** [comment]
Hello I also want to a pairs of points {(q_r, q_t)},i use project on target 1 and save the idx_knn,then i match source_idx and idx_knn. However the result is not right? How can I do?

**Comment by ThibaultGROUEIX** [comment]
I don't know unfortunately. It looks like you may have a bug.
Best regards,
Thibault
