### ISSUE TITLE
Rotation invariance

### ISSUE THREAD

**Issue by kuzand** [ThibaultGROUEIX/3D-CODED#38]
In the paper it says that "As an alternative, we tried to learn a network directly invariant to rotations around the vertical axis."
I was wondering how was this done?

**Comment by ThibaultGROUEIX** [comment]
The dataset of humans is aligned. We added invariance to rotation through data augmentation by randomly rotating the sampled human mesh around the Y axis when training 3D-CODED. This makes the network's job harder but works to some extent.
Best regards,
Thibault

**Comment by kuzand** [comment]
Thank you for the information!
