### ISSUE TITLE
How is the error for correspondences computed?

### ISSUE THREAD

**Issue by kuzand** [ThibaultGROUEIX/3D-CODED#39]
According to the paper, "The error is the average Euclidean distance between the estimated projection and the ground-truth projection.". How exactly is it computed and is it done somewhere in the code? Is it also averaged for all the given pairs of shapes?

**Comment by ThibaultGROUEIX** [comment]
Hi @kuzand,

Thanks for your interest in 3D-CODED. You would not be able to find this in the code unfortunately. Right after this extract comes "We evaluated our method through the online server". The  link is : http://faust.is.tue.mpg.de/challenge/Intra-subject_challenge

The score in indeed averaged on all given pairs. It`s an L2 loss between predicted points and ground-truth points AFAI Remember.

Best regards,
Thibault
