### ISSUE TITLE
errors in Build chamfer distance

### ISSUE THREAD

**Issue by jjcao** [ThibaultGROUEIX/3D-CODED#4]
When executing: python setup.py install, after
'gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -m64 -fPIC -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -m64 -fPIC -fPIC ... -c chamfer_cuda.cpp -o build/temp.linux-x86_64-3.7/chamfer_cuda.o -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11'

I meet lots of errors like "/usr/include/c++/6/tuple:483:67: **error: mismatched argument pack lengths** while expanding ‘std::is_constructible".

My environment is
1. cuda: 9 (Cuda compilation tools, release 9.0, V9.0.176)
2. python: 3.7 (in conda env)
3. gcc: gcc (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424

Could you kindly help me out? or what''s your cuda and gcc version? 
Thank you.

More errors are like these: 
`/home/jack/miniconda3/envs/py37/lib/python3.7/site-packages/torch/lib/include/ATen/TensorMethods.h:646:36:   required from here
/usr/include/c++/6/tuple:483:67: error: mismatched argument pack lengths while expanding ‘std::is_constructible<_Elements, _UElements&&>’
       return __and_<is_constructible<_Elements, _UElements&&>...>::value;
                                                                   ^~~~~
/usr/include/c++/6/tuple:484:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’ not a return-statement
     }
 ^
/usr/include/c++/6/tuple: In instantiation of ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_ImplicitlyMoveConvertibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’:
/usr/include/c++/6/tuple:626:362:   required by substitution of ‘template<class ... _UElements, typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor, at::Tensor, at::Tensor>::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor, at::Tensor, at::Tensor>::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> = <missing>]’
/home/jack/miniconda3/envs/py37/lib/python3.7/site-packages/torch/lib/include/ATen/TensorMethods.h:646:36:   required from here
/usr/include/c++/6/tuple:489:65: error: mismatched argument pack lengths while expanding ‘std::is_convertible<_UElements&&, _Elements>’
       return __and_<is_convertible<_UElements&&, _Elements>...>::value;
`

**Comment by ThibaultGROUEIX** [comment]
Hi @jjcao,

It might be related to a pytorch version issue as AFAIK, building extensions was done differently before pytorch v4. I have tested ```python setup.py install" on pytorchv4 and pytorchv1
My current setup is : 

CUDA 10
Pytorch v1
python 3.7
gcc g++ 7.3

Can you try different gcc version ? gcc5 or 4.7 ? if you want to try gcc7, you'll need cuda10 most likely.

Best,
Thibault

**Comment by ThibaultGROUEIX** [comment]
Also I am currently doing a major upgrade of the code to make things a bit smoother. Please git pull frequently to make sure you have the latest version of the code.  I might introduce some additional typos in the process, so it would be a huge help if you report the error you face during the setup.

**Comment by jjcao** [comment]
Thank you. 
cuda 9 + python: 3.7 + gcc 5 => success

**Comment by awaelchli** [comment]
Hi @ThibaultGROUEIX 
I pulled the latest code and running the same as you, cuda10, pytorch 1.0, python 3.7, gcc 7.3.
When I execute `python setup.py install` I get the error

`cc1plus: error: /usr/lib/x86_64-linux-gnu/libcudnn.so.5/include: Not a directory`

Alongside that it also prints out the gcc command with the include option `-I/usr/lib/x86_64-linux-gnu/libcudnn.so.5/include`. If I change that to 

`-I/usr/lib/x86_64-linux-gnu/libcudnn.so.5`

and rerun the gcc command, it executes without any errors. 
Do you know where I can change this to make the whole installation work with `python setup.py install`?

**Comment by ThibaultGROUEIX** [comment]
I don't have cudnn installed : i don't have the folder ```/usr/lib/x86_64-linux-gnu/libcudnn.so.5```
Maybe just try removing it ? (it could be a mismatch between cudnn version and cuda version maybe).

**Comment by palanglois** [comment]
Hi @awaelchli , 

It's very likely that this error happens because you either set the environment variable 'CUDNN_HOME' or 'CUDNN_PATH'.

From there, 2 possibilites.

- You can remove the env variables, but it is likely that you use it for other projects.

- Otherwise, you can try to add the following lines at the beginning of your setup.py in order to delete the env variables only in the child process : 

`import os`
`if 'CUDNN_HOME' in os.environ: del os.environ['CUDNN_HOME']`
`if 'CUDNN_PATH' in os.environ: del os.environ['CUDNN_PATH']`

Hope it helps,
Pierre-Alain

**Comment by ThibaultGROUEIX** [comment]
awesome, thanks @palanglois !

**Comment by awaelchli** [comment]
Thanks @ThibaultGROUEIX 
After I uninstalled/removed the cudnn, it compiled. However when I import the chamfer module I get

`>>> import chamfer`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/adrian/research/envs/research/lib/python3.7/site-packages/chamfer-0.0.0-py3.7-linux-x86_64.egg/chamfer.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE`

which I have seen in the past when the wrong GCC version was used for compiling. But I double checked it is using GCC 7.3. I also tried gcc 5.

**Comment by ThibaultGROUEIX** [comment]
great news ! from https://discuss.pytorch.org/t/cppextension-loading-complains-undefined-symbol/27908/4 , try to ```import torch``` first

**Comment by awaelchli** [comment]
@ThibaultGROUEIX Oh, wow. Yep that did the trick. That's funny. Thanks!!!
@palanglois  I only saw your answer just now. Indeed I had the CUDNN_HOME variable defined, I think for tensorflow. Now with your post I can leave it there, thanks!
