### ISSUE TITLE
Problems with downloading data

### ISSUE THREAD

**Issue by DavidBoja** [ThibaultGROUEIX/3D-CODED#41]
Hi Thibault,
first of all, thank you for sharing your code with the community.

I have some issues with downloading the data. From what I can gather,there is an issue with authorization. The test data is downloaded, whilst the train data gets an "403: Forbidden" error. I attached a screenshot of the error. Maybe you have some knowledge as to why this is happening.

![Downloading the data](https://user-images.githubusercontent.com/32020857/132869599-c1f774ed-db85-4100-94d2-5290ffd5e5b8.png)

Also, can I ask you why did you save the data in a .pth format?  This way, the data needs to be loaded all at once, which can be infeasible for some.

Thank you in advance for your response.

**Comment by ThibaultGROUEIX** [comment]
Hi @DavidBoja ,

Thanks for your interest in the data/code.
I added manual download links in https://github.com/ThibaultGROUEIX/3D-CODED/commit/2dd1efbb212e522f0057a55ab5b287071e23d28b

You have a valid point about the `.pth`, I simply did not think about it at the time and did what seemed the easiest,
 
Best regards,
Thibault

**Comment by DavidBoja** [comment]
Thank you. The download works now. :)

Got it, I was searching for methods to load the data from the `.pth` file in batches, but haven't found anything. Glad to know I haven't missed anything.

Kind regards,
David
