### ISSUE TITLE
SMALL-R animals dataset

### ISSUE THREAD

**Issue by Sentient07** [ThibaultGROUEIX/3D-CODED#43]
Hello,

From the `data/generate_data_animals.py` I can generate dogs, cows, cats and hippos. However, I would like to generate other categories such as horses - using the SMALL-R dataset you've mentioned in the paper. Can you please help with generating them?
Thanks

**Comment by ThibaultGROUEIX** [comment]
Hi @Sentient07 ,

Thanks for reaching out!
Sorry for the late reply, this is beyond the scope of this codebase, I recommend to reach out directly to the Small-R authors.

best regards,
Thibault

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with 3D-CODED.
Cheers,
Thibault
