### ISSUE TITLE
average Euclidean error on SCAPE

### ISSUE THREAD

**Issue by hhuang-code** [ThibaultGROUEIX/3D-CODED#44]
Hi Thibault,

Can you share the code for calculating the average Euclidean error on SCAPE dataset? Thanks!

**Comment by ThibaultGROUEIX** [comment]
Hi @aaron-h-code,
Thanks a lot for your interest in the code.

I have not kept this part unfortunately, 

Best regards,
Thibault

**Comment by hhuang-code** [comment]
Hi @ThibaultGROUEIX,

Thanks for your quick reply.

Could you just give some hints/steps on how to compute the average Euclidean error, given the prediction and ground-truth correspondence, so I can write the evaluation code to use on other datasets, other than FAUST online evaluation?

Thanks!

Best regards,
Aaron

**Comment by ThibaultGROUEIX** [comment]
On scape, the error is the geodesic distance, not euclidean : 
The dataset : http://ai.stanford.edu/~drago/Projects/scape/scape.html
Geodesic error : looks like you can get both geodesic and data from here if you don't want to reimplement it: https://github.com/ruixiang440/Dual_Iterative_Refinement_Method

Best regards,
Thibault

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with  3D-CODED
Cheers,
Thibault
