### ISSUE TITLE
Training ERRor

### ISSUE THREAD

**Issue by caijinana** [ThibaultGROUEIX/3D-CODED#48]
Hello Dear  @ThibaultGROUEIX professor:
![微信图片_20220308153627](https://user-images.githubusercontent.com/64821543/157190352-645bc320-9176-4985-a0d0-71062d91d73d.png)
when i am training the code i got the error as the picture,but i can training 1 epoch in the morning ,but when i traing again in the afternoon i  got the error, i used training successfully in the january, how should i do ?Thank you

**Comment by ThibaultGROUEIX** [comment]
Hi @caijinana ,
Nice hearing from you again. I have not changed the code since January but you probably switched machines?
I would say you don't have enough RAM to train. You could consider two things:
- use another machine with more RAM
- split the training data into chunks and load the chunk sequentially
Best regards,
Thibault

**Comment by caijinana** [comment]
@ThibaultGROUEIX Thank you very much,now my project is working but i have not change the coda ,So strange ,now i want to ask you another question ,i want to training my own data ,it have 6480 points ,can I set the random_sampling false, but when i set false,i got the error, how can i do ? and set the random_sampling false only  affect the visualization or effect the result?
![微信图片_20220308202807](https://user-images.githubusercontent.com/64821543/157238992-9d71a8cc-6888-4407-95c3-a0c3d306fb67.png)
![微信图片_20220308202826](https://user-images.githubusercontent.com/64821543/157239082-714f1343-dcef-4677-92cf-4e32f88a7c57.png)

**Comment by caijinana** [comment]
![微信图片_20220308203455](https://user-images.githubusercontent.com/64821543/157239231-078ac81f-7b45-4cb5-a4c8-c29e87ac2e4d.png)

**Comment by ThibaultGROUEIX** [comment]
The  bug above is only related to visualisation and does not affect the results.
Visdom is a package similar to tensorboard in case you don't know it. It used to be my favourite but now I mostly use tensorboard.
Bets regards

**Comment by caijinana** [comment]
Thank you very much ,i got the error when i training 1 epoch,and can not get the next data.i use the dataset[index,400:]as my dataset,could you give me some advice?






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月8日(星期二) 晚上10:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThibaultGROUEIX/3D-CODED] Training ERRor (Issue #48)





 
The  bug above is only related to visualisation and does not affect the results.
 Visdom is a package similar to tensorboard in case you don't know it. It used to be my favourite but now I mostly use tensorboard.
 Bets regards
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caijinana** [comment]
![微信图片_20220309090546](https://user-images.githubusercontent.com/64821543/157352443-358383ff-621d-4f78-8859-d1699f9eaba6.png)

**Comment by caijinana** [comment]
Thank you ,Love you 
   Best wishes!
Happy every day!

**Comment by ThibaultGROUEIX** [comment]
Love your spirit ! Cheers
