### ISSUE TITLE
trimesh.io doesn't exist

### ISSUE THREAD

**Issue by Rookiee** [ThibaultGROUEIX/3D-CODED#6]
Thanks for sharing the code. 
I'm using the latest trimesh 2.36.28. The line 58 (`trimesh.io.export.export_mesh(mesh, "results/correspondences.ply")`) in "/inference/correspondences.py" should be modified to `mesh.export("results/correspondences.ply")` so as to make the program run smoothly.

trimesh.io module doesn't exist in 2.36.28.

**Comment by ThibaultGROUEIX** [comment]
Thanks for sharing your feedback! i'll update asap.
best regards,
Thibault
