### ISSUE TITLE
code for generating Figure 5.

### ISSUE THREAD

**Issue by lixiang-ucas** [ThibaultGROUEIX/3D-CODED#7]
Hi,
    Can you share the code for calculating the geodesic error maps (Fig. 5)? Thanks.

**Comment by ThibaultGROUEIX** [comment]
Sure ! It is available here : https://github.com/zorah/KernelMatching/tree/master/tools/geodesic_cpp
Good luck,
Thibault

**Comment by lixiang-ucas** [comment]
Thanks. @ThibaultGROUEIX

**Comment by lixiang-ucas** [comment]
Hi,
    I found it somewhat hard to call the geodesic distance function in KernelMatching. Would it be possible for you to share part of your code for generating the geodesic distance given a source point, a target point, and the reference mesh? Thank you so much for your patience.

**Comment by ThibaultGROUEIX** [comment]
Hi @lixiang-ucas, it is actually pretty messy, i would need to clean it up and i won't have time to do so until the ICCV deadline... Let me know if you urgently need it.
Best regards,
Thibault

**Comment by lixiang-ucas** [comment]
Thank you for your attention. I've figured it out.

**Comment by lixiang-ucas** [comment]
Hi Thibault, I followed the instructions in Kernel Matching repo and successfully generate the desired geodesic distance for FAUST and TOSCA dataset, but failed with SCAPE dataset. The meshes in SCAPE dataset contains holes, which caused errors when calculating the geodesic distances. Can you give me some suggestions for how to figure it out? Thanks.

**Comment by ThibaultGROUEIX** [comment]
hi @lixiang-ucas 
why not use nearest neighbors between the scans with holes and the registered scans ? you should be able to compute geodesic distance on the registered scans i think.
